Update README.md
matu3ba/awesome-cli-rust pull request #1
Opened 2021-07-08 16:30 UTC by sstadick

This is an awesome list, I learned about a few new tools in here. Thanks for adding `hck`!

2021-07-08 17:41 UTC, matu3ba requested changes
can you change the other typo as well? `delimmiter` is not correct. sorry for the inconvenience.

2021-07-12 15:41 UTC, sstadick commented on README.md
> +| hck       | hck       | `cut` with decompression, column reordering and regex as delimmiter | [hck](https://github.com/sstadick/hck)                |  hck    |
```suggestion
| hck       | hck       | `cut` with decompression, column reordering and regex as delimiter | [hck](https://github.com/sstadick/hck)                |  hck    |
```

2021-07-12 15:42 UTC, sstadick commented
Fixed!

2021-07-12 16:43 UTC, merged

2021-07-12 16:43 UTC, matu3ba commented
Thanks for the fix @sstadick.